### ISSUE TITLE
Roadschematics Bug

### ISSUE THREAD

**Issue by AgentLV** [IntellectualCrafters/PlotSquared#108]
Everything worked, but then I found this(I used the regenallroads command):
http://abload.de/img/2015-01-24_14.47.16okzcg.png

**Comment by boy0001** [comment]
Try regenerating the roads again while standing there. Sometimes this happens and I don't quite know why yet.

**Comment by AgentLV** [comment]
Ok thx

**Comment by boy0001** [comment]
*Occurs because chunk.load() only schedules the chunk to be loaded, but doesn't actually load the chunk

**Comment by recon88** [comment]
Yep, just experienced the same issue in a new world. Followed the setup instructions for the road schematic. Newly generated chunks are having the default road instead of the schematic. However regen all roads works fine but shouldn't be the solution.
Hope you can fix this :)

**Comment by boy0001** [comment]
That sounds like a slightly different issue. Can you verify that using worldedit to regenerate a road results in the default rather than schematic based road?

If it does generate the schematic, then it means those are existing chunks which are missing the schematic after the world regeneration.

**Comment by recon88** [comment]
Alright, step by step again:
- I followed the instructions for road schematics
- I did /p regenallworlds
- Took a look and everything around me was fine (schematic roads)
- I did /tp <name> 10000 64 10000 (random distance far away)
- Looked around and found newly generated roads with default settings instead of the schematic

**Comment by boy0001** [comment]
Yep, I'd give that a 100% probability of being newly generated. Did you make sure the regeneration finished? I'll assume you did, so no need to answer that unless the problem magically solves itself. That sounds like an easy way to test the feature, so I'll go right ahead and let you know if I'm able to easily fix it.

**Comment by boy0001** [comment]
Cannot replicate, after conversion the chunks generated just fine.

**Comment by recon88** [comment]
What am I doing wrong then?

**Comment by boy0001** [comment]
I'd tell you if I knew. Could you send me a copy of your startup log?

**Comment by recon88** [comment]
Alright, I guess I got it now. I didn't know that I **must** set the road and wall height to 0.
For new chunks it took the road settings instead of the schematic while I had the height set to 64.
Now it's working perfectly fine.

I guess we really need some #comments in the config file which explain all the options :)
Or just a wiki page for that.

**Comment by boy0001** [comment]
Bukkit doesn't support commenting on existing files, we would need to replace the existing functions with our own. Wiki page would be much easier.

**Comment by recon88** [comment]
You could put the config file into the jar. That allows you to comment everything :)
Just call saveDefaultConfig() in your onEnable() and it will save the config.yml into /plugins/plugin-name/
Doesn't overwrite the existing config.yml

**Comment by boy0001** [comment]
*I'm closing this as it's getting slightly sidetracked. @recon88 I'll create a new issue for you about your road schematics.
