### ISSUE TITLE
Armor stands can be broken by anyone in plots

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualCrafters/PlotSquared#125]
Pretty much as the title says, armor stand can be broken by anyone regardless of being added to a plot or not

git-Spigot-952179b-bbf72f3
plotsquared 2.6.3

**Comment by recon88** [comment]
They can also be placed by anyone in any plot. Plus everyone can take out or put on armor from ArmorStands.
Having both issues.

For taking/putting Armor:
There's a new Event which can be cancelled: PlayerInteractAtEntityEvent
That disallows interaction with ArmorStands.

For breaking: 
EntityDamageByEntityEvent needs an additional check: (e.getEntity() instanceof ArmorStand)

For Placing:
Placing ArmorStand doesn't trigger the BlockPlaceEvent as far as I know. Therefore we need an additional check for ArmorStands in the PlayerInteractEvent and cancel it always. 
The problem is the "plots.admin.interact.other". I guess he is using that like I do. I want players to be able to interact with buttons etc but I don't want them to place Armorstands. 
This also includes Boats and Minecarts. They need to be added to the ArmorStand check as well.
Otherwise you can spam them everywhere with the interact permission.

**Comment by PhanaticD** [comment]
this was actually fixed for the most part, at least the breaking is, just in the config set pve: false

**Comment by recon88** [comment]
Good to know :) So we just need the other things to be fixed.
