### ISSUE TITLE
Plot clearing chunk updates not properly transferred to client

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualCrafters/PlotSquared#167]
I had a weird issue right now which is probably very difficult to recreate.

I cleared a plot and wondered that a 16x16x16 chunk somewhere at height 100 has not been cleared. Obviously another player also saw that some blocks were not cleared and started to break those...well I saw that he touches various blocks but I saw he did not break them. He had gamemode creative.
Then I tried to break these blocks and it worked for me but he probably did not see the breaking though. After a relog the "uncleared" blocks disappeared.

My conclusion is that this chunk has not been updated at client side after clearing. Maybe a CB/Spigot issue?

Used default clearing, not debugclear.
PS 2.7.4 @ Spigot

**Comment by boy0001** [comment]
This was actually very easy to replicate:
 - Use worldedit to select the plot and //expand vert
 - Set the entire plot to stone
 - clear the plot

We use NMS to modify blocks and send the chunk updates. The issue is entirely on our end, not necesssarily with Spigot/Craftbukkit. 

We do however use a new chunk update rather than individual block updates as it's a lot quicker. It's possible that sending a new chunk to a client who can already see the chunk is what might cause the issue. If that is the case, would it be worthwhile sacrificing a lot of performance to fix this issue?

**Comment by EvilOlaf** [comment]
Ha awesome.

Hard to answer. As server owner I would say "no, just relog and it's gone", as player I would say "yes, because I don't care about server problems".

Does debugclear has a different solution for this issue?

**Comment by boy0001** [comment]
Debug clear uses a different approach to setting the blocks, but the same client chunk updates.

**Comment by EvilOlaf** [comment]
I think this should depend in how many other peope criticize this issue and then decide if it should be fixed or not.
All things considered it is just an optical issue.

**Comment by dextonanderson** [comment]
Many of my players have complained about this issue. I think it would be worth considering sacrificing performance to fix.

**Comment by boy0001** [comment]
Temporary fix for next version: Use debugclear, as it actually seems to work.

**Comment by boy0001** [comment]
The latest version should mostly address this issue. Please reopen if it's still causing problems.
