### ISSUE TITLE
Cannot do /p visit

### ISSUE THREAD

**Issue by Kyle1264x** [IntellectualCrafters/PlotSquared#201]
Error when doing p visit <name>
http://pastebin.com/3P2EgfYe

Suggestion:
allow /p home <name>:<plot>

**Comment by boy0001** [comment]
Thanks. I'll take a look now and update this in the next few minutes.

**Comment by boy0001** [comment]
It looks like an issue with ChatControl. Are you having it do anything to the teleport messages?

**Comment by Kyle1264x** [comment]
http://pastebin.com/hQ2sCUN5

Heres the chatcontrol config. Havent done anything with it.

**Comment by boy0001** [comment]
I recommend updating ChatControl, and if it still doesn't work, contact kangarko and send the stacktrace.

**Comment by kangarko** [comment]
The problem is that an empty (null) message is printed into the server's console, which result in an error. 
This can be issue of this plugin printing null messages in console.

Please note that in the latest version of my ChatControl I ignore these messages so if the you update it should be "fixed"
