### ISSUE TITLE
PlotSquared cannot block interact event of Mod item

### ISSUE THREAD

**Issue by CatMe0w** [IntellectualCrafters/PlotSquared#288]
Take AE2 Mod as a example, select the quartz wrench and HOLD LSHIFT TO RIGHT CLICK THE BLOCK OF THIS MOD, this block will drop without any PlotSquared permissions.

**Comment by boy0001** [comment]
PlotSquared uses standard block break and interact events and cancels them when required. If a player doesn't have permission for an area, AND PlotSquared is cancelling any called events, there's not much more I can do.

After looking into the AE2 GitHub repo, and there are two flaws in how protection is implemented:
Firstly it doesn't check if a plugin cancels a PlayerInteractEvent:
https://github.com/TheFantasyCraft/Forge-Permittor/blob/master/src/main/java/com/fantasycraft/forgepermittor/listeners/ProtectionListener.java#L41

Secondly, instead of using the standard event system, it is reliant on custom hooks for every protection plugin:
https://github.com/TheFantasyCraft/Forge-Permittor/blob/master/src/main/java/com/fantasycraft/forgepermittor/protection/ProtectionManager.java

@thomas15v
The simple fix would not be for PlotSquared to develop a hook, but rather for AE2 to check the PlayerInteractEvent properly AND for it to use the standard event system for block protection rather than custom hooks. This can be done by calling and checking the result of the event:
``` java
Bukkit.getServer().getPluginManager().callEvent(event);
if (!event.isCancelled()) {
    // Do something
}
```

**Comment by thomas15v** [comment]
@boy0001 so far I know my AE2 still bypasses my plugin. The mod sends custom packets that pypasses   cauldron/bukkits event system.

**Comment by boy0001** [comment]
That's disappointing. Sorry @CatMe0w :(
