### ISSUE TITLE
Build anywhere 

### ISSUE THREAD

**Issue by Dylan376** [IntellectualCrafters/PlotSquared#312]
I am currently on 
Version 2.11.6 on Spigot 1.7.9 and my players are able to build anywhere. I noticed on Monday there was a post about the same thing but i figured it must have been fixed due to all the patches. If there is any way to fix this i would be grateful.

from,
omcolorful.com

**Comment by boy0001** [comment]
It wasn't a valid bug as it couldn't be replicated under normal circumstances. The person also failed to provide any information apart from saying it didn't work.

All the updated were a mix of fixes and new features, but not related to building on roads. If you can send me the following it will help resolve your problem:

if you updated the plugin or installed it
settings.yml
startup log
make sure the user isn't op or has since relogged after being deopped
result of the following permission checks:
 - plots.admin
 - plots.admin.interact.other
 - plots.admin.interact.road

To check permissions:
pex: /pex user <user> check <permission>
groupmanager: /manucheckp <user> <permission>

**Comment by boy0001** [comment]
closed until further clarification
