### ISSUE TITLE
Players able to build everywhere, including plots.

### ISSUE THREAD

**Issue by iSmokeWeed** [IntellectualCrafters/PlotSquared#316]
**What I did** : Simply installed the plugin
**What console says** : Now this varies, the first try at fixing this came up with 'this version of worldedit is not supported by plotsquared' so I updated it and no longer the error. Ive tried regening a world or creating more but no luck

**What is happening** Players are able to build anywhere they please, in other plots or in the roads. They have 0 Plotme permissions.
Ive checked the config nothing seems off, I have worldguard and worldedit, no errors in console , region protection just isnt working.

Running Craftbukkit 1.8.3
Runnign PlotSquared 2.11.8

**Comment by boy0001** [comment]
Could you send me the following?
name of the world in question
result of /plot info 
settings.yml
startup log
make sure the user isn't op or has since relogged after being deopped
result of the following permission checks:
 - plots.admin
 - plots.admin.interact.other
 - plots.admin.interact.unowned
 - plots.admin.interact.road

To check permissions:
pex: `/pex user <user> check <permission>`
groupmanager: `/manucheckp <user> <permission>`

**Comment by boy0001** [comment]
closed until further clarification
