### ISSUE TITLE
Delete a plot remotely

### ISSUE THREAD

**Issue by dukesmart** [IntellectualCrafters/PlotSquared#338]
A player's plot causes other players to crash whenever near; as such, I cannot be on the plot to clear it with /plot clear or /plot delete. Please add the functionality to delete a plot by coordinates id or by username.

**Comment by boy0001** [comment]
Use: `plot clear <X;Z> <world>`
Where `<X;Z>` is a plot id e.g. 5;-3
And `<world>` is the name of the world

The issue is probably from excess entities / blockstates. You could also try enabling the PlotSquared chunk processor which will prevent this from occurring in the future (depending on the configuration)

https://github.com/IntellectualCrafters/PlotSquared/wiki/Chunk-processor
